language: node_js
node_js: 
  - "stable"
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --disable-gpu --remote-debugging-port=9876 http://localhost &
script:
  - cd trust-pool-app && npm run travis