language: node_js
node_js: 
  - "stable"
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable  
script:
  - cd trust-pool-app && npm run travis