language: node_js
node_js: 
  - "stable"
sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --disable-gpu --remote-debugging-port=9876 http://0.0.0.0:9876/ &
script:
  - cd trust-pool-app && npm run travis